namespace AutomatedRealms.DataImportUtility.Tests.SampleData;

internal static partial class ImportDataObjects
{
    /// <summary>
    /// Sample CSV data for testing.
    /// </summary>
    internal const string ImportCsv = """
        "Lab Sample ID","Client Sample ID","Matrix","Sample Type","Collection Date","Percent Moisture","Analysis Method","Dilution Factor","Analysis Date","CAS","Analyte","Result","Unit","Flag","High Limit","High Limit Type","Low Limit","Low Limit Type","Percent Recovery","Lower Recovery Limit","Upper Recovery Limit","RPD","RPD Limit","Receipt Lab","Project Description","SDG","Lab Job ID","COC ID","Sample Type Desc","Receive Date","Total Sample Amount","Total Sample Amount Units","Leach Batch","Leach Method","Leach Date","Prep Batch","Prep Method","Prep Date","Prep Type","Initial Amount","Initial Amount Unit","Final Amount","Final Amount Unit","Re-Analysis Type","Analysis Batch","Analysis Lab","Instrument ID","Column_Detector ID","Basis","Analyte Type","Result Status","TPU","TPU Sigma","Decision Level","Retention Time","Spike Amount","Expected Amount","RER","RER Limit","Lower Breech Limit","Upper Breech Limit"
        "280-190533-1","PNEFEF","Water","","04/24/2024 07:35","","GCMSMS_NDMA","1","05/02/2024 16:32","62-75-9","N-Nitrosodimethylamine","2.5","ng/L","","2.1","RL","0.33","MDL","","","","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","952.1","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.006","","","","","",""
        "280-190533-1","PNEFEF","Water","","04/24/2024 07:35","","GCMSMS_NDMA","1","05/02/2024 16:32","17829-05-9","N-Nitrosodimethylamine-d6","66","ng/L","","","","","","63","25","150","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","952.1","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.060","105","","","","",""
        "280-190533-2","PNEFEF DUP","Water","","04/24/2024 07:35","","GCMSMS_NDMA","1","05/02/2024 16:51","62-75-9","N-Nitrosodimethylamine","2.5","ng/L","","2.1","RL","0.32","MDL","","","","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","962","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.006","","","","","",""
        "280-190533-2","PNEFEF DUP","Water","","04/24/2024 07:35","","GCMSMS_NDMA","1","05/02/2024 16:51","17829-05-9","N-Nitrosodimethylamine-d6","56","ng/L","","","","","","53","25","150","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","962","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.059","104","","","","",""
        "280-190533-3","PNININ","Water","","04/24/2024 07:55","","GCMSMS_NDMA","1","05/02/2024 17:10","62-75-9","N-Nitrosodimethylamine","11","ng/L","","2.1","RL","0.33","MDL","","","","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","948.4","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","6.996","","","","","",""
        "280-190533-3","PNININ","Water","","04/24/2024 07:55","","GCMSMS_NDMA","1","05/02/2024 17:10","17829-05-9","N-Nitrosodimethylamine-d6","61","ng/L","","","","","","58","25","150","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","948.4","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.059","105","","","","",""
        "280-190533-4","PNUVEF","Water","","04/24/2024 07:45","","GCMSMS_NDMA","1","05/02/2024 17:29","62-75-9","N-Nitrosodimethylamine","2.5","ng/L","","2.1","RL","0.33","MDL","","","","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","942","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","6.996","","","","","",""
        "280-190533-4","PNUVEF","Water","","04/24/2024 07:45","","GCMSMS_NDMA","1","05/02/2024 17:29","17829-05-9","N-Nitrosodimethylamine-d6","61","ng/L","","","","","","57","25","150","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","942","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.059","106","","","","",""
        "280-190533-5","PNUVIN","Water","","04/24/2024 07:50","","GCMSMS_NDMA","1","05/02/2024 17:48","62-75-9","N-Nitrosodimethylamine","11","ng/L","","2.1","RL","0.32","MDL","","","","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","970.4","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","6.996","","","","","",""
        "280-190533-5","PNUVIN","Water","","04/24/2024 07:50","","GCMSMS_NDMA","1","05/02/2024 17:48","17829-05-9","N-Nitrosodimethylamine-d6","59","ng/L","","","","","","57","25","150","","","Eurofins Denver","NBCS NDMA Analysis Study","","280-190533-1","","","04/24/2024 11:00","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","970.4","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.060","103","","","","",""
        "LCS 320-758850/2-A","","Water","LCS","","","GCMSMS_NDMA","1","05/02/2024 15:15","62-75-9","N-Nitrosodimethylamine","19.4","ng/L","","2.0","RL","0.31","MDL","97","62","149","4","20","","NBCS NDMA Analysis Study","","280-190533-1","","Lab Control Sample","","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","1000","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Spike","PRIMARY","","","","7.006","20.0","","","","",""
        "LCS 320-758850/2-A","","Water","LCS","","","GCMSMS_NDMA","1","05/02/2024 15:15","17829-05-9","N-Nitrosodimethylamine-d6","55.4","ng/L","","","","","","55","25","150","","","","NBCS NDMA Analysis Study","","280-190533-1","","Lab Control Sample","","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","1000","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.059","100","","","","",""
        "LCSD 320-758850/3-A","","Water","LCSD","","","GCMSMS_NDMA","1","05/02/2024 15:34","62-75-9","N-Nitrosodimethylamine","20.1","ng/L","","2.0","RL","0.31","MDL","100","62","149","4","20","","NBCS NDMA Analysis Study","","280-190533-1","","Lab Control Sample Duplicate","","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","1000","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Spike","PRIMARY","","","","7.006","20.0","","","","",""
        "LCSD 320-758850/3-A","","Water","LCSD","","","GCMSMS_NDMA","1","05/02/2024 15:34","17829-05-9","N-Nitrosodimethylamine-d6","42.3","ng/L","","","","","","42","25","150","","","","NBCS NDMA Analysis Study","","280-190533-1","","Lab Control Sample Duplicate","","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","1000","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.059","100","","","","",""
        "MB 320-758850/1-A","","Water","MB","","","GCMSMS_NDMA","1","05/02/2024 14:56","62-75-9","N-Nitrosodimethylamine","ND","ng/L","","2.0","RL","0.31","MDL","","","","","","","NBCS NDMA Analysis Study","","280-190533-1","","Method Blank","","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","1000","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.006","","","","","",""
        "MB 320-758850/1-A","","Water","MB","","","GCMSMS_NDMA","1","05/02/2024 14:56","17829-05-9","N-Nitrosodimethylamine-d6","59.9","ng/L","","","","","","60","25","150","","","","NBCS NDMA Analysis Study","","280-190533-1","","Method Blank","","","","","","","320-758850","3535","05/01/2024 09:54","Total/NA","1000","mL","0.5","mL","","320-759503","Eurofins Sacramento","SV9","","WET","Target","PRIMARY","","","","7.059","100","","","","",""
        
        """;

    /// <summary>
    /// Sample JSON data for testing.
    /// </summary>
    internal const string ImportJson = """
        [
          {
            "Lab Sample ID": "280-190533-1",
            "Client Sample ID": "PNEFEF",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:35",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 16:32",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 2.5,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2.1,
            "High Limit Type": "RL",
            "Low Limit": 0.33,
            "Low Limit Type": "MDL",
            "Percent Recovery": "",
            "Lower Recovery Limit": "",
            "Upper Recovery Limit": "",
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 952.1,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.006,
            "Spike Amount": "",
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-1",
            "Client Sample ID": "PNEFEF",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:35",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 16:32",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 66,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 63,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 952.1,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.06,
            "Spike Amount": 105,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-2",
            "Client Sample ID": "PNEFEF DUP",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:35",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 16:51",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 2.5,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2.1,
            "High Limit Type": "RL",
            "Low Limit": 0.32,
            "Low Limit Type": "MDL",
            "Percent Recovery": "",
            "Lower Recovery Limit": "",
            "Upper Recovery Limit": "",
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 962,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.006,
            "Spike Amount": "",
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-2",
            "Client Sample ID": "PNEFEF DUP",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:35",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 16:51",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 56,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 53,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 962,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.059,
            "Spike Amount": 104,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-3",
            "Client Sample ID": "PNININ",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:55",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 17:10",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 11,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2.1,
            "High Limit Type": "RL",
            "Low Limit": 0.33,
            "Low Limit Type": "MDL",
            "Percent Recovery": "",
            "Lower Recovery Limit": "",
            "Upper Recovery Limit": "",
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 948.4,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 6.996,
            "Spike Amount": "",
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-3",
            "Client Sample ID": "PNININ",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:55",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 17:10",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 61,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 58,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 948.4,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.059,
            "Spike Amount": 105,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-4",
            "Client Sample ID": "PNUVEF",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:45",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 17:29",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 2.5,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2.1,
            "High Limit Type": "RL",
            "Low Limit": 0.33,
            "Low Limit Type": "MDL",
            "Percent Recovery": "",
            "Lower Recovery Limit": "",
            "Upper Recovery Limit": "",
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 942,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 6.996,
            "Spike Amount": "",
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-4",
            "Client Sample ID": "PNUVEF",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:45",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 17:29",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 61,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 57,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 942,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.059,
            "Spike Amount": 106,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-5",
            "Client Sample ID": "PNUVIN",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:50",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 17:48",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 11,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2.1,
            "High Limit Type": "RL",
            "Low Limit": 0.32,
            "Low Limit Type": "MDL",
            "Percent Recovery": "",
            "Lower Recovery Limit": "",
            "Upper Recovery Limit": "",
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 970.4,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 6.996,
            "Spike Amount": "",
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "280-190533-5",
            "Client Sample ID": "PNUVIN",
            "Matrix": "Water",
            "Sample Type": "",
            "Collection Date": "04/24/2024 07:50",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 17:48",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 59,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 57,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "Eurofins Denver",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "",
            "Receive Date": "04/24/2024 11:00",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 970.4,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.06,
            "Spike Amount": 103,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "LCS 320-758850/2-A",
            "Client Sample ID": "",
            "Matrix": "Water",
            "Sample Type": "LCS",
            "Collection Date": "",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 15:15",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 19.4,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2,
            "High Limit Type": "RL",
            "Low Limit": 0.31,
            "Low Limit Type": "MDL",
            "Percent Recovery": 97,
            "Lower Recovery Limit": 62,
            "Upper Recovery Limit": 149,
            "RPD": 4,
            "RPD Limit": 20,
            "Receipt Lab": "",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "Lab Control Sample",
            "Receive Date": "",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 1000,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Spike",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.006,
            "Spike Amount": 20,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "LCS 320-758850/2-A",
            "Client Sample ID": "",
            "Matrix": "Water",
            "Sample Type": "LCS",
            "Collection Date": "",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 15:15",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 55.4,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 55,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "Lab Control Sample",
            "Receive Date": "",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 1000,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.059,
            "Spike Amount": 100,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "LCSD 320-758850/3-A",
            "Client Sample ID": "",
            "Matrix": "Water",
            "Sample Type": "LCSD",
            "Collection Date": "",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 15:34",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": 20.1,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2,
            "High Limit Type": "RL",
            "Low Limit": 0.31,
            "Low Limit Type": "MDL",
            "Percent Recovery": 100,
            "Lower Recovery Limit": 62,
            "Upper Recovery Limit": 149,
            "RPD": 4,
            "RPD Limit": 20,
            "Receipt Lab": "",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "Lab Control Sample Duplicate",
            "Receive Date": "",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 1000,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Spike",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.006,
            "Spike Amount": 20,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "LCSD 320-758850/3-A",
            "Client Sample ID": "",
            "Matrix": "Water",
            "Sample Type": "LCSD",
            "Collection Date": "",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 15:34",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 42.3,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 42,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "Lab Control Sample Duplicate",
            "Receive Date": "",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 1000,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.059,
            "Spike Amount": 100,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "MB 320-758850/1-A",
            "Client Sample ID": "",
            "Matrix": "Water",
            "Sample Type": "MB",
            "Collection Date": "",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 14:56",
            "CAS": "62-75-9",
            "Analyte": "N-Nitrosodimethylamine",
            "Result": "ND",
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": 2,
            "High Limit Type": "RL",
            "Low Limit": 0.31,
            "Low Limit Type": "MDL",
            "Percent Recovery": "",
            "Lower Recovery Limit": "",
            "Upper Recovery Limit": "",
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "Method Blank",
            "Receive Date": "",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 1000,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.006,
            "Spike Amount": "",
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          },
          {
            "Lab Sample ID": "MB 320-758850/1-A",
            "Client Sample ID": "",
            "Matrix": "Water",
            "Sample Type": "MB",
            "Collection Date": "",
            "Percent Moisture": "",
            "Analysis Method": "GCMSMS_NDMA",
            "Dilution Factor": 1,
            "Analysis Date": "05/02/2024 14:56",
            "CAS": "17829-05-9",
            "Analyte": "N-Nitrosodimethylamine-d6",
            "Result": 59.9,
            "Unit": "ng/L",
            "Flag": "",
            "High Limit": "",
            "High Limit Type": "",
            "Low Limit": "",
            "Low Limit Type": "",
            "Percent Recovery": 60,
            "Lower Recovery Limit": 25,
            "Upper Recovery Limit": 150,
            "RPD": "",
            "RPD Limit": "",
            "Receipt Lab": "",
            "Project Description": "NBCS NDMA Analysis Study",
            "SDG": "",
            "Lab Job ID": "280-190533-1",
            "COC ID": "",
            "Sample Type Desc": "Method Blank",
            "Receive Date": "",
            "Total Sample Amount": "",
            "Total Sample Amount Units": "",
            "Leach Batch": "",
            "Leach Method": "",
            "Leach Date": "",
            "Prep Batch": "320-758850",
            "Prep Method": 3535,
            "Prep Date": "05/01/2024 09:54",
            "Prep Type": "Total/NA",
            "Initial Amount": 1000,
            "Initial Amount Unit": "mL",
            "Final Amount": 0.5,
            "Final Amount Unit": "mL",
            "Re-Analysis Type": "",
            "Analysis Batch": "320-759503",
            "Analysis Lab": "Eurofins Sacramento",
            "Instrument ID": "SV9",
            "Column_Detector ID": "",
            "Basis": "WET",
            "Analyte Type": "Target",
            "Result Status": "PRIMARY",
            "TPU": "",
            "TPU Sigma": "",
            "Decision Level": "",
            "Retention Time": 7.059,
            "Spike Amount": 100,
            "Expected Amount": "",
            "RER": "",
            "RER Limit": "",
            "Lower Breech Limit": "",
            "Upper Breech Limit": ""
          }
        ]
        """;
}