name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        
      # Build the solution
      - name: Build
        run: dotnet build src/DataImportUtility/DataImportUtility.sln -p:GHPages=true -o:public -c:Release

      # Run the tests
      - name: Test
        run: dotnet test src/DataImportUtility/DataImportUtility.sln -c:Release

      # If the tests succeed, move the *.nupkg files to the artifacts directory

      